services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.3
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic

  cybersec-jade:
    build: .
    container_name: cybersec-jade
    ports:
      - "7890:7890"
      - "1099:1099"
    depends_on:
      - elasticsearch
    networks:
      - elastic
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

volumes:
  es_data:
    driver: local

networks:
  elastic:
    driver: bridge